disk:
  service: Disk
  root: <%= ENV['WORKDIR'] || '.' %>/attachments
  public: <%= ENV['ACTIVE_STORAGE_PUBLIC'] == 'true' %>

test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>
  public: true
